version: "3"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - 443:443
    depends_on:
     - wordpress
    volumes:
     - wp_vol:/var/www/html
    networks:
     - inception
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    env_file: ./.env
    depends_on: 
      - mariadb
    volumes:
      - wp_vol:/var/www/html/
    networks:
      - inception
    restart: on-failure
  
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    env_file: ./.env
    volumes:
     - db_vol:/var/lib/mysql
    networks:
     - inception
    restart: on-failure

networks:
  inception:

volumes:
  wp_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/lmasson/data/wp_vol
      o: bind
 
  db_vol:
    driver: local
    driver_opts:
      type: none
      device : /home/lmasson/data/db_vol
      o: bind
